# Generated by Django 4.1.3 on 2023-05-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirecter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='isPoliticalNews',
            field=models.BooleanField(default=False),
        ),
    ]
